name: Only Tests
on:
  push:
    branches:
      - main

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-Java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarosal/setup-maven@4.4
        with:
          maven-version: 3.8.2

      - name: All tests and coverage check
        run: mvn clean install
